apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "seriohub-velero.fullname" . }}-watchdog
  # name: velero-watchdog
  labels:
    app: velero-watchdog
    tier: backend
  {{- include "seriohub-velero.labels" . | nindent 4 }}
  {{- with .Values.watchdog.veleroMonitoring.annotations }}
  annotations: {{ toYaml . | nindent 4 }}
  {{- end }}
spec:
  replicas: {{ .Values.watchdog.replicas }}
  selector:
    matchLabels:
      tier: backend
    {{- include "seriohub-velero.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        app: velero-watchdog
        tier: backend
      {{- include "seriohub-velero.selectorLabels" . | nindent 8 }}
      {{- with .Values.watchdog.veleroMonitoring.annotations }}
      annotations: {{ toYaml . | nindent 8 }}
      {{- end }}
    spec:
      {{- with .Values.watchdog.veleroMonitoring.volumes }}
      volumes:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.watchdog.veleroMonitoring.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- if .Values.watchdog.veleroMonitoring.podSecurityContext.enabled }}
      securityContext:
        {{- toYaml (omit .Values.watchdog.veleroMonitoring.podSecurityContext "enabled") | nindent 8 }}
      {{- end }}
      {{- with .Values.watchdog.veleroMonitoring.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.watchdog.veleroMonitoring.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.watchdog.veleroMonitoring.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      containers:
      - env:
        - name: POD_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        - name: POD_NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        envFrom:
        {{- if lookup "v1" "ConfigMap" .Release.Namespace "velero-watchdog-user-config" }}
        - configMapRef:
            name: velero-watchdog-user-config
        {{- end }}
        - configMapRef:
            name: vui-watchdog-config
        - configMapRef:
            name: vui-helm-config
        - secretRef:
            name: vui-watchdog-secret
        image: {{ .Values.watchdog.veleroMonitoring.image.registry | trimSuffix "/" }}/{{ .Values.watchdog.veleroMonitoring.image.repository }}:{{ .Values.watchdog.veleroMonitoring.image.tag }}
        imagePullPolicy: {{ .Values.watchdog.veleroMonitoring.imagePullPolicy }}
        name: velero-monitoring
        {{- if .Values.watchdog.veleroMonitoring.securityContext.enabled }}
        securityContext:
          {{- toYaml (omit .Values.watchdog.veleroMonitoring.securityContext "enabled") | nindent 10 }}
        {{- end }}
        {{- with .Values.watchdog.veleroMonitoring.resources }}
        resources:
          {{ . | toYaml | nindent 10 }}
        {{- end }}
        {{- with .Values.watchdog.veleroMonitoring.volumeMounts }}
        volumeMounts:
          {{- toYaml . | nindent 10 }}
        {{- end }}
      serviceAccountName: {{ include "seriohub-velero.fullname" . }}-readonly-sa
