apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ include "seriohub-velero.fullname" . }}-k8s-read-only-role
  labels:
  {{- include "seriohub-velero.labels" . | nindent 4 }}
rules:
- apiGroups:
  - "*"
  resources:
  - "*"
  verbs:
  - get
  - list
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ include "seriohub-velero.fullname" . }}-k8s-read-only-role-binding
  labels:
  {{- include "seriohub-velero.labels" . | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: "{{ include "seriohub-velero.fullname" . }}-k8s-read-only-role"
subjects:
- kind: ServiceAccount
  name: "{{ include "seriohub-velero.fullname" . }}-k8s-read-only-service-account"
  namespace: "{{ .Release.Namespace }}"