apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: {{ include "seriohub-velero.fullname" . }}-vui-read-only-role
  namespace: "{{ .Release.Namespace }}"
  labels:
    {{- include "seriohub-velero.labels" . | nindent 4 }}
rules:
  - apiGroups: [""]
    resources: ["configmaps"]
    verbs: ["get", "list", "watch"]
  - apiGroups: [""]
    resources: ["secrets"]
    verbs: ["get", "list", "watch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ include "seriohub-velero.fullname" . }}-vui-read-only-role-binding
  labels:
  {{- include "seriohub-velero.labels" . | nindent 4 }}
  namespace: "{{ .Release.Namespace }}"
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: "{{ include "seriohub-velero.fullname" . }}-vui-read-only-role"
subjects:
- kind: ServiceAccount
  name: "{{ include "seriohub-velero.fullname" . }}-k8s-read-only-service-account"
  namespace: "{{ .Release.Namespace }}"