{{- with .Values.watchdogConfig }}
apiVersion: v1
kind: Secret
metadata:
  name: vui-watchdog-secret
  labels:
    {{- include "seriohub-velero.labels" $ | nindent 4 }}
type: Opaque
stringData:
  APPRISE: {{- $apprise := list }}
    {{- if eq (upper (toString .emailEnable)) "TRUE" }}
      {{- $apprise = append $apprise (printf "mailtos://%s:%s@%s?to=%s&format=markdown" .emailAccount .emailPassword .emailSmtpServer .emailRecipients) }}
    {{- end }}
    {{- if eq (upper (toString .slackEnable)) "TRUE" }}
      {{- $apprise = append $apprise (printf "slack://%s/#%s" .slackToken .slackChannel) }}
    {{- end }}
    {{- if eq (upper (toString .telegramEnable)) "TRUE" }}
      {{- $apprise = append $apprise (printf "tgram://%s/%s" .telegramToken .telegramChatId) }}
    {{- end }}
    {{- if gt (len $apprise) 0 }}
      {{ join ";" $apprise }}
    {{- else }}
      ""
    {{- end }}
{{- end }}
