{{- with .Values.watchdogService.config }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "seriohub-velero.fullname" $ }}-watchdog-secret
  labels:
    {{- include "seriohub-velero.labels" $ | nindent 4 }}
type: Opaque
stringData:
  APPRISE: |
    {{- if and (hasKey . "apprise") (ne .apprise "") }}
      {{ .apprise }}
    {{- else }}
      {{- $apprise := list }}
      {{- if .emailEnable }}
        {{- $apprise = append $apprise (printf "mailtos://%s:%s@%s?to=%s&format=markdown" .emailAccount .emailPassword .emailSmtpServer .emailRecipients) }}
      {{- end }}
      {{- if .slackEnable }}
        {{- $apprise = append $apprise (printf "slack://%s/#%s" .slackToken .slackChannel) }}
      {{- end }}
      {{- if .telegramEnable }}
        {{- $apprise = append $apprise (printf "tgram://%s/%s" .telegramToken .telegramChatId) }}
      {{- end }}
      {{- if gt (len $apprise) 0 }}
        {{ join ";" $apprise }}
      {{- else }}
        ""
      {{- end }}
    {{- end }}
{{- end }}

