apiVersion: v1
kind: Service
metadata:
  name: {{ include "seriohub-velero.fullname" . }}-watchdog
  labels:
  {{- include "seriohub-velero.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  selector:
    app: velero-watchdog
  {{- include "seriohub-velero.selectorLabels" . | nindent 4 }}
  ports:
    - port: {{ .Values.watchdogClusterip.port }}
      protocol: TCP
      targetPort: {{ .Values.watchdogClusterip.targetPort }}
