apiVersion: v1
kind: Service
metadata:
  name: {{ include "seriohub-velero.fullname" . }}-watchdog-clusterip-svc
  labels:
  {{- include "seriohub-velero.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  selector:
    component: watchdog
  {{- include "seriohub-velero.selectorLabels" . | nindent 4 }}
  ports:
  {{- .Values.watchdogService.deployment.ports | toYaml | nindent 2 }}
