{{- if .Values.apiService.deployment.storage.enabled }}
{{- with .Values.apiService.deployment.storage }}
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: {{ include "seriohub-velero.fullname" $ }}-vui-api-pvc
spec:
  storageClassName: {{ .storageClassName }}
  {{- with .accessModes }}
  accessModes: 
    {{- toYaml . | nindent 4 }}
  {{- end }}
  resources:
    {{- toYaml .resources | nindent 4 }}
{{- end }}
{{- end }}