apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: {{ include "seriohub-velero.fullname" . }}-api-mgmt-role
  namespace: "{{ .Release.Namespace }}"
  labels:
    {{- include "seriohub-velero.labels" . | nindent 4 }}
rules:
  - apiGroups: [""]
    resources: ["configmaps"]
    verbs: ["*"]
  - apiGroups: [""]
    resources: ["pods/log"]
    verbs: ["*"]
  - apiGroups: ["batch"]
    resources: ["cronjobs"]
    verbs: ["get", "list", "watch"]
  - apiGroups: [""]
    resources: ["secrets"]
    verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
  - apiGroups: ["apps"]
    resources: ["deployments"]
    verbs: ["get", "patch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ include "seriohub-velero.fullname" . }}-api-role-binding
  labels:
  {{- include "seriohub-velero.labels" . | nindent 4 }}
  namespace: "{{ .Release.Namespace }}"
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: "{{ include "seriohub-velero.fullname" . }}-api-mgmt-role"
subjects:
- kind: ServiceAccount
  name: "{{ include "seriohub-velero.fullname" . }}-api-sa"
  namespace: "{{ .Release.Namespace }}"