{{- if not .Values.apiConfig.existingSecret -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "seriohub-velero.secretName" . }}
  labels:
  {{- include "seriohub-velero.labels" $ | nindent 4 }}
type: Opaque
  {{- with .Values.apiConfig }}
stringData:
  RESTIC_PASSWORD: {{ .resticPassword | quote }}
  {{- if not (quote .securityTokenKey | empty)  }}
  SECURITY_TOKEN_KEY: {{ .securityTokenKey }}
  {{- end }}
  DEFAULT_ADMIN_USERNAME: {{ .defaultAdminUsername | quote }}
  DEFAULT_ADMIN_PASSWORD: {{ .defaultAdminPassword | quote }}
  {{- end }}
{{- end -}}
