{{- if not (default "" .Values.apiService.secret.existingSecret) }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "seriohub-velero.fullname" . }}-api-secret
  labels:
  {{- include "seriohub-velero.labels" $ | nindent 4 }}
type: Opaque
stringData:
{{- with .Values.apiService.secret }}
  DEFAULT_ADMIN_USERNAME: {{ .defaultAdminUsername | quote }}
  DEFAULT_ADMIN_PASSWORD: {{ .defaultAdminPassword | quote }}
  RESTIC_PASSWORD: {{ .resticPassword | quote }}

  {{- if not (quote .securityTokenKey | empty) }}
  SECURITY_TOKEN_KEY: {{ .securityTokenKey }}
  {{- end }}

  # LDAP
  {{- if eq ($.Values.auth.mode | upper) "LDAP" }}
  LDAP_BIND_PASSWORD: {{ $.Values.auth.ldap.bindPassword | quote }}
  {{- end }}

  # NATS
  {{- if or $.Values.global.core $.Values.apiService.nats.enabled }}
  NATS_USERNAME: {{ .natsUsername | quote }}
  NATS_PASSWORD: {{ .natsPassword | quote }}
  {{- end }}
{{- end -}}
{{- end -}}