{{- if .Values.global.core }}
{{- with .Values.apiConfig }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: vui-core-config
  labels:
  {{- include "seriohub-velero.labels" $ | nindent 4 }}
data:
  API_ENABLE_DOCUMENTATION: {{ .apiEnableDocumentation | quote }}
  API_ENDPOINT_URL: {{ .apiEndpointUrl | quote }}
  API_ENDPOINT_PORT: {{ .apiEndpointPort | quote }}

  API_RATE_LIMITER_CUSTOM_1: {{ .apiRateLimiterCustom1 | quote }}  
  API_RATE_LIMITER_L1: {{ .apiRateLimiterL1 | quote }}
  API_TOKEN_EXPIRATION_MIN: {{ .apiTokenExpirationMin | quote }}
  API_TOKEN_REFRESH_EXPIRATION_DAYS: {{ .apiTokenRefreshExpirationDays | quote }}

  BUILD_VERSION: dev

  DEBUG_LEVEL: {{ .debugLevel | quote }}

  CLUSTER_ID: {{ $.Values.global.clusterName | quote  }}   
  
  K8S_IN_CLUSTER_MODE: {{ $.Values.global.k8SInclusterMode | quote  }} 
  K8S_VELERO_NAMESPACE: {{ $.Values.global.veleroNamespace }}
  K8S_VELERO_UI_NAMESPACE: {{ $.Release.Namespace }}
  
  NATS_ENDPOINT_URL:  {{ $.Values.nats.ip | quote }}
  
  #
  # AUTHENTICATION
  #
  AUTH_ENABLED: {{ $.Values.authentication.enabled | quote }}
  AUTH_TYPE: {{ $.Values.authentication.type | quote }}
  {{- if eq ($.Values.authentication.type | upper) "LDAP" }}
  # LDAP authentication
  LDAP_URI: {{ $.Values.authentication.ldap.uri | quote }}
  LDAP_USE_SSL: {{ $.Values.authentication.ldap.useSsl | quote }}
  LDAP_BASE_DN: {{ $.Values.authentication.ldap.baseDn | quote }}
  LDAP_BIND_DN: {{ $.Values.authentication.ldap.bindDn | quote }}
  LDAP_USER_SEARCH_FILTER: {{ $.Values.authentication.ldap.userSearchFilter | quote }}
  # LDAP authz
  {{- if eq ($.Values.authentication.ldap.authz.enabled | upper) "TRUE" }}  
  LDAP_AUTHZ_ENABLED: {{ $.Values.authentication.ldap.authz.enabled | quote }}
  LDAP_AUTHZ_STRATEGY: {{ $.Values.authentication.ldap.authz.strategy | quote }}
  LDAP_AUTHZ_BASE_DN: {{ $.Values.authentication.ldap.authz.authzBaseDn | quote }}
  LDAP_AUTHZ_FILTER: {{ $.Values.authentication.ldap.authz.authzFilter | quote }}
  LDAP_AUTHZ_ATTRIBUTE: {{ $.Values.authentication.ldap.authz.authzAttribute | quote }}
  LDAP_AUTHZ_VALUE: {{ $.Values.authentication.ldap.authz.authzValue | quote }}
  {{- end }}
  {{- end }}
  
{{- end }}
{{- end }}