{{- if .Values.coreConfig.storage.enabled }}
  {{- with .Values.coreConfig.storage }}
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: pvc-vui-core
spec:
  storageClassName: {{ .storageClassName }}
  {{- with .accessModes }}
  accessModes: 
    {{- toYaml . | nindent 4 }}
  {{- end }}
  resources:
    {{- toYaml .resources | nindent 4 }}
  {{- end }}
{{- end }}
