{{- if .Values.global.core }}
{{- if not (default "" .Values.coreService.secret.existingSecret) }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "seriohub-velero.fullname" $ }}-core-secret
  labels:
  {{- include "seriohub-velero.labels" $ | nindent 4 }}
type: Opaque
stringData:
{{- with .Values.coreService.secret }}
  DEFAULT_ADMIN_USERNAME: {{ .defaultAdminUsername | quote }}
  DEFAULT_ADMIN_PASSWORD: {{ .defaultAdminPassword | quote }}
  
  {{- if not (quote .securityTokenKey | empty)  }}
  SECURITY_TOKEN_KEY: {{ .securityTokenKey }}
  {{- end }}
  
  CLIENT_KEY: {{ .clientKey | quote }}
  
  # LDAP
  {{- if eq ($.Values.auth.mode | upper) "LDAP" }}
  LDAP_BIND_PASSWORD: {{ $.Values.auth.ldap.bindPassword | quote }}
  {{- end }}
  
  # NATS
  NATS_USERNAME: {{ .natsUsername | quote }}
  NATS_PASSWORD: {{ .natsPassword | quote }}
  AAAA: BBBB
{{- end -}}
{{- end -}}
{{- end -}}
