{{- if .Values.global.core }}
{{- if not .Values.coreConfig.existingSecret -}}
apiVersion: v1
kind: Secret
metadata:
  name: vui-core-secret
  labels:
  {{- include "seriohub-velero.labels" $ | nindent 4 }}
type: Opaque
  {{- with .Values.coreConfig }}
stringData:
  {{- if not (quote .securityTokenKey | empty)  }}
  SECURITY_TOKEN_KEY: {{ .securityTokenKey }}
  {{- end }}
  DEFAULT_ADMIN_USERNAME: {{ .defaultAdminUsername | quote }}
  DEFAULT_ADMIN_PASSWORD: {{ .defaultAdminPassword | quote }}
  {{- end }}
  
   # LDAP
  {{- if eq (.Values.authentication.type | upper) "LDAP" }}
  LDAP_BIND_PASSWORD: {{ $.Values.authentication.ldap.bindPassword | quote }}
  {{- end }}
  
  # NATS
  NATS_USERNAME: {{ $.Values.nats.username | quote }}
  NATS_PASSWORD: {{ $.Values.nats.password | quote }}
{{- end -}}
{{- end }}
