{{- if eq .Values.exposure.mode "nodePort" }}
{{- if .Values.global.core }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "seriohub-velero.fullname" . }}-core-nodeport-svc
  labels:
  {{- include "seriohub-velero.labels" . | nindent 4 }}
spec:
  type: NodePort
  selector:
    component: core
  {{- include "seriohub-velero.selectorLabels" . | nindent 4 }}
  ports:
    - nodePort: {{ .Values.exposure.nodePort.apiPort }}
      port: 80
      targetPort: api
{{- end }}
{{- end }}