{{- if .Values.global.core }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "seriohub-velero.fullname" . }}-core-clusterip-svc
  labels:
    {{- include "seriohub-velero.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  selector:
    component: core
  ports:
    - name: vui-core
      port: 80
      targetPort: api
      protocol: TCP
{{- end }}