apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: {{ include "seriohub-velero.fullname" . }}-velero-admin
  labels:
  {{- include "seriohub-velero.labels" . | nindent 4 }}
  namespace: {{ .Values.global.veleroNamespace }}
rules:
  # Allows create, update, and read access to ConfigMaps in the namespace
  - apiGroups:
      - ""
    resources:
      - configmaps
    verbs:
      - create
      - update
      - get
      - list

  # Allows create, update, and read access to Secrets in the namespace
  - apiGroups:
      - ""
    resources:
      - secrets
    verbs:
      - create
      - update
      - get
      - list

  # Allows read-only access to Pods for monitoring purposes
  - apiGroups:
      - ""
    resources:
      - pods
    verbs:
      - get
      - list
      - watch
  
 # Grants full permissions to all Velero-related custom resources
  - apiGroups:
      - velero.io
    resources:
      - "*"
    verbs:
      - "*"

  # Grants full access to view and manage Pod logs
  - apiGroups:
      - ""
    resources:
      - pods/log
    verbs:
      - "*"

---

apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ include "seriohub-velero.fullname" . }}-velero-admin-binding
  labels:
  {{- include "seriohub-velero.labels" . | nindent 4 }}
  namespace: {{ .Values.global.veleroNamespace }}

# Binds the Role to the specified ServiceAccount within the Velero namespace
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: {{ include "seriohub-velero.fullname" . }}-velero-admin

subjects:
  # Grants the Role permissions to the ServiceAccount
  - kind: ServiceAccount
    name: {{ include "seriohub-velero.fullname" . }}-admin-sa
    namespace: {{ .Release.Namespace }}