apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "seriohub-velero.fullname" . }}-admin-sa
  labels:
  {{- include "seriohub-velero.labels" . | nindent 4 }}
  annotations:
    {{- toYaml .Values.global.serviceAccounts.adminServiceAccount.annotations | nindent 4 }}
