apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: {{ include "seriohub-velero.fullname" . }}-admin
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "seriohub-velero.labels" . | nindent 4 }}
rules:
  # Grants full access (create, read, update, delete) to ConfigMaps in the namespace
  - apiGroups:
      - ""
    resources:
      - configmaps
    verbs:
      - "*"

  # Grants full access to Pods in the namespace
  - apiGroups: 
      - ""
    resources: 
      - "pods"
    verbs: 
      - "*"

  # Grants full access to Pod logs in the namespace
  - apiGroups:
      - ""
    resources:
      - pods/log
    verbs:
      - "*"

  # Allows read-only access to CronJobs for monitoring purposes
  - apiGroups:
      - batch
    resources:
      - cronjobs
    verbs:
      - get
      - list
      - watch

  # Grants full access to Secrets in the namespace
  - apiGroups:
      - ""
    resources:
      - secrets
    verbs:
      - "*"

  # Allows reading and patching Deployments (e.g. for updating images)
  - apiGroups:
      - apps
    resources:
      - deployments
    verbs:
      - get
      - patch

---

apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ include "seriohub-velero.fullname" . }}-admin-binding
  labels:
  {{- include "seriohub-velero.labels" . | nindent 4 }}
  namespace: {{ .Release.Namespace }}

# Binds the admin Role to the specified ServiceAccount in the same namespace
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: {{ include "seriohub-velero.fullname" . }}-admin

subjects:
  # Assigns the Role permissions to the specified ServiceAccount
  - kind: ServiceAccount
    name: {{ include "seriohub-velero.fullname" . }}-admin-sa
    namespace: {{ .Release.Namespace }}