apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ include "seriohub-velero.fullname" . }}-namespace-readonly
  labels:
    {{- include "seriohub-velero.labels" . | nindent 4 }}

# Defines a ClusterRole that grants read-only access to all namespaces in the cluster
rules:
  - apiGroups:
      - ""
    resources:
      - namespaces
    verbs:
      - get
      - list

---

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ include "seriohub-velero.fullname" . }}-namespace-readonly-binding
  labels:
  {{- include "seriohub-velero.labels" . | nindent 4 }}

# Binds the namespace-readonly ClusterRole to a specific ServiceAccount
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ include "seriohub-velero.fullname" . }}-namespace-readonly

subjects:
  # Assigns the read-only ClusterRole permissions to the specified ServiceAccount
  - kind: ServiceAccount
    name: {{ include "seriohub-velero.fullname" . }}-readonly-sa
    namespace: {{ .Release.Namespace }}

