apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: {{ include "seriohub-velero.fullname" . }}-velero-readonly
  labels:
  {{- include "seriohub-velero.labels" . | nindent 4 }}
  namespace: {{ .Values.global.veleroNamespace }}
rules:
  # Grants read-only access to ConfigMaps in the Velero namespace
  - apiGroups:
      - ""
    resources:
      - configmaps
    verbs:
      - get
      - list
      - watch

  # Grants read-only access to all Velero-related custom resources in the namespace
  - apiGroups:
      - velero.io
    resources:
      - "*"
    verbs:
      - get
      - list
      - watch

---

apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ include "seriohub-velero.fullname" . }}-velero-readonly-binding
  labels:
  {{- include "seriohub-velero.labels" . | nindent 4 }}
  namespace: {{ .Values.global.veleroNamespace }}

# Binds the velero-readonly Role to a specific ServiceAccount in the Velero namespace
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: {{ include "seriohub-velero.fullname" . }}-velero-readonly

subjects:
  # # Assigns the Role permissions to the specified ServiceAccount
  - kind: ServiceAccount
    name: {{ include "seriohub-velero.fullname" . }}-readonly-sa
    namespace: {{ .Release.Namespace }}