apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: {{ include "seriohub-velero.fullname" . }}-readonly
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "seriohub-velero.labels" . | nindent 4 }}

# Defines a Role that grants read-only access to ConfigMaps and Secrets in the namespace
rules:
  - apiGroups:
      - ""
    resources:
      - configmaps
    verbs:
      - get
      - list
      - watch

  - apiGroups:
      - ""
    resources:
      - secrets
    verbs:
      - get
      - list
      - watch

---

apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ include "seriohub-velero.fullname" . }}-readonly-binding
  labels:
  {{- include "seriohub-velero.labels" . | nindent 4 }}
  namespace: {{ .Release.Namespace }}

# Binds the readonly Role to a specific ServiceAccount in the namespace
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: {{ include "seriohub-velero.fullname" . }}-readonly

subjects:
  # Assigns the read-only Role permissions to the specified ServiceAccount
  - kind: ServiceAccount
    name: {{ include "seriohub-velero.fullname" . }}-readonly-sa
    namespace: {{ .Release.Namespace }}