apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "seriohub-velero.fullname" . }}-readonly-sa
  labels:
  {{- include "seriohub-velero.labels" . | nindent 4 }}
  annotations:
    {{- toYaml .Values.k8SReadOnlyServiceAccount.serviceAccount.annotations | nindent 4 }}
