{{- if not .Values.global.agentMode }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "seriohub-velero.fullname" $ }}-ui-config
  labels:
    {{- include "seriohub-velero.labels" . | nindent 4 }}
data:
  # Configuration
  NEXT_PUBLIC_AUTH_ENABLED: {{ .Values.auth.enabled | quote }}
  NEXT_PUBLIC_REFRESH_DATATABLE_AFTER: {{ .Values.uiService.config.nextPublicRefreshDatatableAfter | quote }}
  NEXT_PUBLIC_REFRESH_RECENT: {{ .Values.uiService.config.nextPublicRefreshRecent | quote  }}
  NEXT_PUBLIC_LOGGER_ENABLED: {{ .Values.uiService.config.nextPublicLoggerEnabled | quote  }}
  
  {{- if not .Values.global.core }}
  # API Agent Name
  NEXT_PUBLIC_VELERO_API_NAME_1: {{ .Values.global.clusterName | quote  }}  
  {{- else }}
  NEXT_PUBLIC_LOGIN_CLUSTERS_SWITCH: "true"
  NEXT_PUBLIC_VELERO_API_NAME_1: "{{ .Values.global.clusterName  }}-core"
  {{- end }}

  # Exposure ingress
  {{- if eq .Values.exposure.mode "ingress" }}
  NEXT_PUBLIC_VELERO_API_URL_1: {{ printf "https://%s/api" (index (index .Values.exposure.ingress.spec.tls 0).hosts 0) | quote }}
  NEXT_PUBLIC_VELERO_API_WS_1: {{ printf "wss://%s" (index (index .Values.exposure.ingress.spec.tls 0).hosts 0) | quote }}
  {{- end }}
  
  # Exposure nodePort
  {{- if eq .Values.exposure.mode "nodePort" }}
  NEXT_PUBLIC_VELERO_API_URL_1: {{ printf "http://%s:%s/api" .Values.exposure.nodePort.ip (toString .Values.exposure.nodePort.apiPort) | quote }}
  NEXT_PUBLIC_VELERO_API_WS_1: {{ printf "ws://%s:%s" .Values.exposure.nodePort.ip (toString .Values.exposure.nodePort.apiPort) | quote }}
  {{- end }}

  # Exposure clusterIP
  {{- if eq .Values.exposure.mode "clusterIP" }}
  NEXT_PUBLIC_VELERO_API_URL_1: "http://{{ .Values.exposure.clusterIP.localAddress }}:{{ .Values.exposure.clusterIP.apiPort }}/api"
  NEXT_PUBLIC_VELERO_API_WS_1: "ws://{{ .Values.exposure.clusterIP.localAddress }}:{{ .Values.exposure.clusterIP.apiPort }}"
  {{- end }}

  # Prototype Inspect Backups Features
  NEXT_PUBLIC_INSPECT_BACKUP_ENABLED: {{ .Values.apiService.config.inspectBackupEnabled | quote  }}
{{- end }}
