{{- if not .Values.global.agentMode }}
{{- if .Values.uiNp.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "seriohub-velero.fullname" . }}-ui-np
  labels:
  {{- include "seriohub-velero.labels" . | nindent 4 }}
spec:
  type: NodePort
  selector:
    layer: webserver
  {{- include "seriohub-velero.selectorLabels" . | nindent 4 }}
  ports:
    - nodePort: {{ .Values.uiNp.uiPort }}
      port: 80
      targetPort: run
{{- end }}
{{- end }}