{{- if not .Values.global.agentMode }}
{{- if or .Values.uiIngress.enabled .Values.clusterIpService.enabled}}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "seriohub-velero.fullname" . }}-ui
  labels:
  {{- include "seriohub-velero.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  selector:
    app:  vui-ui
  {{- include "seriohub-velero.selectorLabels" . | nindent 4 }}
  ports:
	{{- .Values.ui.ports | toYaml | nindent 2 }}
{{- end }}
{{- end }}